<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.e69Nya5' shared service.

return $this->privates['.service_locator.e69Nya5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'employe' => ['privates', '.errored..service_locator.e69Nya5.App\\Entity\\Employe', NULL, 'Cannot autowire service ".service_locator.e69Nya5": it references class "App\\Entity\\Employe" but no such service exists.'],
], [
    'employe' => 'App\\Entity\\Employe',
]);
