<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIOY4vnx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIOY4vnx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIOY4vnx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIOY4vnx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIOY4vnx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IOY4vnx',
    'container.build_id' => 'd820bec5',
    'container.build_time' => 1563071612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIOY4vnx');
